# Generated by Django 5.0.2 on 2024-04-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_converasationmessage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converasationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversation'),
        ),
    ]
